### ISSUE TITLE
Setup IAM access for HOT-OAM Server development

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-server#17]
@dodobas please coordinate with @mojodna and @lossyrob on requirements and grant access through IAM on HOT's AWS

**Comment by dodobas** [comment]
@mojodna, @lossyrob what do you need?

**Comment by sethfitz** [comment]
"Power user" IAM access is probably easiest, if that works for you.  (A quick list of services that we'll probably get our hands dirty with includes S3, EC2 / ELB, ECS, Cloudfront, Cloudformation, SQS, SWF, IAM instance roles.)

Alternately, we could set up a secondary AWS account for sandboxing purposes (where we'd move stuff over as it gets sorted, except for data in S3, which would start on the HOT account) and link it to the HOT account for billing.

Thoughts?

**Comment by cgiovando** [comment]
Single HOT account if possible. DevSeed will have access as well to migrate their OAM apps in.

**Comment by hectcastro** [comment]
Our accounts now have access to create and associate IAM roles.
